### ISSUE TITLE
How to generate offline plans

### ISSUE THREAD

**Issue by lzk23** [amflorio/dvrp-stochastic-requests#1]
Hello,
   Thanks for sharing the code. 
   I have compiled the code using Makefile and generate the executable file, i.e.. dvrpsr. "./dvrpsr 21 V-0.4-UTI-5-50 ../reqs/V-0.4-UTI.1.req ../offline_plans/V-0.4-UTI-5.pb.op", the command is executed. An error information is shown as following:

_Instance(): code: V-0.4-UTI-5-50
loading Vienna network ...
Lambda: 0.4
space-time distribution: uti (0)
number of vehicles: 5
length of the service period: 600 minutes
setting up node types based on spatial dist. and clusters ...
pre-processing shortest-paths ...
2000/16080 done
4000/16080 done
6000/16080 done
8000/16080 done
10000/16080 done
12000/16080 done
14000/16080 done
16000/16080 done
finished pre-processing shortest-paths
readRequests: read 42 static and 228 dynamic requests
loading offline plan from ../offline_plans/V-0.4-UTI-5.pb.op ...
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
Aborted (core dumped)_

  I guess it is because that the offline plans given were not fit my system. My system is Ubuntu. So, i want to regenerate the offline plans. The command to generate offline plans is prescribed as: ./dvrpsr <mode> <inst. code> <reqs. file> <routes file> <offl. plan file>. However, i don't know how to specify the "routes file". Could you detail how to generate offline plans. 

Thanks a lot!

**Comment by amflorio** [comment]
Hey, could you please confirm which version of Boost libraries you have
installed in your system?
You might be able to quick-fix by switching to a different version.

**Comment by lzk23** [comment]
Thanks for your reply. 
I have switched Boost to a different version (from 1.65 to 1.72.0). However, the problem remains. Could i regenerate the offline plans.

**Comment by amflorio** [comment]
Hey,

I've just been able to run out-of-the-box in a Linux environment with boost
1.78.

You may upgrade to boost 1.78.  Otherwise, if you want to create an offline
plan, you first run:

$ ./dvrpsr 3 V-0.4-UTI-5-10 ../reqs/V-0.4-UTI.5.req out.routes myo.op

The command above takes a while (around 15 min on my computer).  This will
apply column generation, then save the myopic plan to file 'myo.op', and
save the pool of routes generated by column generation to file
'out.routes'.  Only then you can generate the potential-based offline plan:

$ ./dvrpsr 4 V-0.4-UTI-5-10 ../reqs/V-0.4-UTI.5.req out.routes pb.op

The command above will read the routes saved on 'out.routes', then generate
a potential-based plan and save it to 'pb.op'.

We cannot generate a potential-based plan directly by column generation
because the cost of a route is non-linear.  Then you can use the generated
plans to run your simulations.

Hope that helps, let me know if that works in your environment.

Regards,
Alexandre

**Comment by lzk23** [comment]
Hello, 
   After i create the offline plans as the instructions you given, the problem is solved. Now everything is ok.
   Thanks a lot!!

Regards,
zekang

**Comment by amflorio** [comment]
Hi Zekang, no problem!  Happy DVRPing!
